apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: smallstep-acme
spec:
  acme:
    server: https://192.168.1.222:9000/acme/acme/directory
    email: you@example.com
    privateKeySecretRef:
      name: smallstep-acme-account-key
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJuekNDQVVhZ0F3SUJBZ0lSQU1RSVFmUnhwbGlxaFJaZy83a1Y4MW93Q2dZSUtvWkl6ajBFQXdJd0xqRVIKTUE4R0ExVUVDaE1JVEdGaVUxTklRMEV4R1RBWEJnTlZCQU1URUV4aFlsTlRTRU5CSUZKdmIzUWdRMEV3SGhjTgpNall3TnpFM01UZ3lORFF5V2hjTk16WXdOekUwTVRneU5EUXlXakF1TVJFd0R3WURWUVFLRXdoTVlXSlRVMGhEClFURVpNQmNHQTFVRUF4TVFUR0ZpVTFOSVEwRWdVbTl2ZENCRFFUQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDkKQXdFSEEwSUFCRVBIWTZyS0xXRjhuaVkrQzR1dWUwbFZWRXB3NmwyZlpYSnBoZ0ZPSlVkRTJiOFZQTEkzYXBEcAp0NjUrbWI0N0FWS1RPdlUxdVh1R1BqZE1UWlNBb1BHalJUQkRNQTRHQTFVZER3RUIvd1FFQXdJQkJqQVNCZ05WCkhSTUJBZjhFQ0RBR0FRSC9BZ0VCTUIwR0ExVWREZ1FXQkJTN21JWG1WVmFsNmNBWTllUW9GYUE2ZlZQVW1UQUsKQmdncWhrak9QUVFEQWdOSEFEQkVBaUFJQVJ4Sm0vaDQ2SGpZU2w3dThxY3ZESmlFc29MVlk0V2pQam1KaXZGUwpLd0lnR2d5N1ZyUDM3MGZzWEdQWmdPZUZZemJPL2l3ZzZIN0xTNEFMa3N3WDRRUT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    solvers:
    - http01:
        ingress:
          class: nginx
