apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: smallstep-acme
spec:
  acme:
    server: https://192.168.1.222:9000/acme/acme/directory
    email: you@example.com
    privateKeySecretRef:
      name: smallstep-acme-account-key
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJuekNDQVVhZ0F3SUJBZ0lSQVBmK2FSMHgyZVN1WEpnZjRMZDkwV0V3Q2dZSUtvWkl6ajBFQXdJd0xqRVIKTUE4R0ExVUVDaE1JVEdGaVUxTklRMEV4R1RBWEJnTlZCQU1URUV4aFlsTlRTRU5CSUZKdmIzUWdRMEV3SGhjTgpNalV4TWpBek1UVXlOelEwV2hjTk16VXhNakF4TVRVeU56UTBXakF1TVJFd0R3WURWUVFLRXdoTVlXSlRVMGhEClFURVpNQmNHQTFVRUF4TVFUR0ZpVTFOSVEwRWdVbTl2ZENCRFFUQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDkKQXdFSEEwSUFCRDI0YzJOUWZLQlNNdFJQVE9DcGtIcTE4TlNBTFlLdjVxTzFiTDJCajBJZ0QwTjNPM3NNbVBrVgplU3M3VE5Ndlc4eHpCZ28wNUR1T2xlT0dhb0hxSk1halJUQkRNQTRHQTFVZER3RUIvd1FFQXdJQkJqQVNCZ05WCkhSTUJBZjhFQ0RBR0FRSC9BZ0VCTUIwR0ExVWREZ1FXQkJURkRUOEkrc1k5R0lYN2QrVUlwNzdCWVM0dmh6QUsKQmdncWhrak9QUVFEQWdOSEFEQkVBaUJ0NzhsMlR1dmNqYVVZdXFiSC9ySnRWU2x6VVN5ZjZYdmp3ZnNadWd5cAp2Z0lnYk53TFNrd1dYV3AzVE9pdnpvVVFqN3VYSGlhUG0zbzR1WVZrUWF1ZG5QTT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    solvers:
    - http01:
        ingress:
          class: nginx
