apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: smallstep-acme
spec:
  acme:
    server: https://192.168.1.222:9000/acme/acme/directory
    email: you@example.com
    privateKeySecretRef:
      name: smallstep-acme-account-key
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJuekNDQVVhZ0F3SUJBZ0lSQUpiaXNnUXpka1F1dWdUSXl3aHhuVjh3Q2dZSUtvWkl6ajBFQXdJd0xqRVIKTUE4R0ExVUVDaE1JVEdGaVUxTklRMEV4R1RBWEJnTlZCQU1URUV4aFlsTlRTRU5CSUZKdmIzUWdRMEV3SGhjTgpNalV4TVRFd01EZ3lPREExV2hjTk16VXhNVEE0TURneU9EQTFXakF1TVJFd0R3WURWUVFLRXdoTVlXSlRVMGhEClFURVpNQmNHQTFVRUF4TVFUR0ZpVTFOSVEwRWdVbTl2ZENCRFFUQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDkKQXdFSEEwSUFCUDFVMHRLQ016VmNOcEFPLzF0ZGFzRGtDQ2hxYkdhR1puNW10d05lZmFKOVlUNGlVdzRxMWN0QwpVOHBXZWFGR1R5eVJvVzBWTzZnRDRESEJPaHIzdlJ5alJUQkRNQTRHQTFVZER3RUIvd1FFQXdJQkJqQVNCZ05WCkhSTUJBZjhFQ0RBR0FRSC9BZ0VCTUIwR0ExVWREZ1FXQkJRd0pSRVBjVVFvR2hUZmtOU090K3ZpcHJmNHR6QUsKQmdncWhrak9QUVFEQWdOSEFEQkVBaUJ0RWgxdDJIL1BZaUowR2thdTZzRlcvb1ZBb3lyQkRCT05sc29oNG9taQo0UUlnWFFxUWtKMERkNmZlRm1UQUJIRnF3dmFtM1F5WFNjQ0hMN0Zqd2o1LytsQT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    solvers:
    - http01:
        ingress:
          class: nginx
