services:
  proxy:
    build:
      context: ./infra/proxy
    container_name: proxy
    network_mode: "host"
    restart: always
    ports:
      - "80:80"
      - "443:443"

  coredns:
    image: coredns/coredns:latest
    container_name: coredns
    restart: unless-stopped
    ports:
      - "${HOST_IP}:53:53/udp"
      - "${HOST_IP}:53:53/tcp"
    volumes:
      - ./infra/coredns/Corefile:/Corefile:ro
      - ./infra/coredns/zones:/zones:rw
    command: ["-conf", "/Corefile"]
    networks:
      - labdockernet # change this name if DOCKER_NETWORK_NAME is modified in genesys.sh

  smallstep:
    image: smallstep/step-ca:latest
    container_name: smallstep
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - smallstep_data:/home/step
    environment:
      - DOCKER_STEPCA_INIT_NAME=LabSSHCA
      - DOCKER_STEPCA_INIT_DNS_NAMES=localhost,smallstep.${LAB_DOMAIN},${HOST_IP}
      - DOCKER_STEPCA_INIT_PASSWORD=___KEEP_IT_OR_CHANGE_IT___
      - DOCKER_STEPCA_INIT_SSH=true
    networks:
      labdockernet: # change this name if DOCKER_NETWORK_NAME is modified in genesys.sh
        aliases:
          - smallstep.${LAB_DOMAIN}

  ansible:
    build:
      context: ./infra/ansible
    container_name: ansible
    hostname: ansible
    network_mode: "host"
    restart: always
    depends_on:
      smallstep:
        condition: service_started
    volumes:
      - ${LAB_PATH}/infra/ansible/entrypoint.sh:/entrypoint.sh
      - ${LAB_PATH}/infra/ansible/playbooks:/playbooks
      - ${LAB_PATH}/infra/ansible/inventories:/inventories
      - ${LAB_PATH}/infra/ansible/roles:/roles
      - ${LAB_PATH}/infra/kubernetes:/kubernetes
      - ansible_key_exchange:/key_exchange
    environment:
      HOST_IP: ${HOST_IP}
      HOST_USER: ${USER}

      CA_HOST: smallstep.${LAB_DOMAIN}
      CA_PORT: "9000"
      CA_URL: https://smallstep.${LAB_DOMAIN}:9000

      ANSIBLE_INVENTORY: /inventories/lab/hosts.ini
      EXCHANGE_DIR: /key_exchange
      ROOT_EX: /key_exchange/root_ca.crt
      ROOT_SHA: /key_exchange/root_ca.crt.sha256
      STEP_ROOT_DIR: /etc/pki/step
      ROOT_DST: /etc/pki/step/root_ca.crt
      STEP_DEFAULTS: /root/.step/config/defaults.json

      K8S_MASTER_HOST: ${K8S_MASTER_HOST}
      K8S_MASTER_IP: ${K8S_MASTER_IP}
      K8S_WORKER1_HOST: ${K8S_WORKER1_HOST}
      K8S_WORKER1_IP: ${K8S_WORKER1_IP}
      K8S_WORKER2_HOST: ${K8S_WORKER2_HOST}
      K8S_WORKER2_IP: ${K8S_WORKER2_IP}

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: always
    environment:
      - ROOT_URL=http://gitea.${LAB_DOMAIN}/
    volumes:
      - gitea_data:/data
    ports:
      - "3000:3000"
      - "2222:22"
    networks:
      - labdockernet # change this name if DOCKER_NETWORK_NAME is modified in genesys.sh

  jenkins:
    build:
      context: ./infra/jenkins
    container_name: jenkins
    restart: always
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - labdockernet # change this name if DOCKER_NETWORK_NAME is modified in genesys.sh

  registry:
    image: registry:2
    container_name: registry
    restart: always
    volumes:
      - registry_data:/var/lib/registry
    ports:
      - "5000:5000"
    networks:
      - labdockernet # change this name if DOCKER_NETWORK_NAME is modified in genesys.sh

networks:
  labdockernet: # change this name if DOCKER_NETWORK_NAME is modified in genesys.sh
    external: true

volumes:
  smallstep_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${LAB_PATH}/dockerdata/smallstep

  gitea_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${LAB_PATH}/dockerdata/gitea

  jenkins_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${LAB_PATH}/dockerdata/jenkins

  registry_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${LAB_PATH}/dockerdata/registry

  ansible_key_exchange:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${LAB_PATH}/dockerdata/ansible_key_exchange

