# promeheus-deployment.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
  namespace: telemetry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  serviceName: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      serviceAccountName: prometheus
      containers:
        - name: prometheus
          image: prom/prometheus:v2.45.0
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
            - "--storage.tsdb.retention.time=24h"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus
            - name: prometheus
              mountPath: /prometheus
            - name: prometheus-token
              mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              readOnly: true
            - name: prometheus-rules
              mountPath: /etc/prometheus/rules
              readOnly: true
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
        - name: prometheus-token
          projected:
            sources:
            - serviceAccountToken:
                path: token
            - configMap:
                name: kube-root-ca.crt
                items:
                - key: ca.crt
                  path: ca.crt
        - name: prometheus-rules
          configMap:
            name: prometheus-rules
      securityContext:
        fsGroup: 65534
        runAsGroup: 65534
        runAsUser: 65534
  volumeClaimTemplates:
  - metadata:
      name: prometheus
    spec:
      storageClassName: local-path
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 3Gi
